### PR TITLE
Proxy support added to the notebook.

### PR DESCRIPTION
**Pull request by DEKHTIARJonathan**
Exact same file,  duplicate the function get_png_image(url) with one including proxy support.

Then the user choose the desired version of the function.

Preview of changes : http://nbviewer.ipython.org/github/DEKHTIARJonathan/neural-nets-are-weird/blob/master/notebooks/neural-nets-are-weird.ipynb

capture1

### CODE REVIEW

**Comment by jvns** [comment]
hey thanks so much for this contribution! Can you make the choice of whether to use a proxy a constant instead of requiring that the person picks a cell to execute?

**Comment by DEKHTIARJonathan** [comment]
Alright, I'll manage to do this. 
I will also add some extensive details in the Readme.md for the Docker parts as it was me who helped to solve the "Docker issue". 

Did you have a look for the 2 issues I raised? Can't manage to fix them... 

Thanks a lot Julia, very nice work!

**Comment by jvns** [comment]
pushed an update for those issues; let me know if it still doesn't work!

**Comment by DEKHTIARJonathan** [comment]
I will apply new changes for the proxy settings.
Your changes are perfectly working

**Pull request closed without merging**
